// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DynLBServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Comm;

class DynLBServerHandler : virtual public DynLBServerIf {
 public:
  DynLBServerHandler() {
    // Your initialization goes here
  }

  void SendJobsToRemote(const int32_t size, const std::vector<std::string> & vJobs) {
    // Your implementation goes here
    printf("SendJobsToRemote\n");
  }

  void RequestJobsFromRemote(const int32_t nJobs) {
    // Your implementation goes here
    printf("RequestJobsFromRemote\n");
  }

  void SendStateToRemote(const std::string& stateBlob) {
    // Your implementation goes here
    printf("SendStateToRemote\n");
  }

  void RequestStateFromRemote() {
    // Your implementation goes here
    printf("RequestStateFromRemote\n");
  }

};
/*
int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DynLBServerHandler> handler(new DynLBServerHandler());
  shared_ptr<TProcessor> processor(new DynLBServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}
*/
